#!/bin/bash
# vim: filetype=sh
# bash_locals
# Description: contains shell functions, variables, aliases etc
#   specific to local machine.

## ENVIRONMENT VARIABLES
## =====================

## PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=/usr/local/go/bin:$PATH

## VARIABLES
## =========

src="$HOME/src"
pjs="$src/projects"
dotfiles="$src/cli/dotfiles"

## ALIASES
## =======

# vim
alias vim="nvim"

## user aliases
alias scipy="ipython --profile=scipy"
alias letssketch="cd $pjs/sketchpad"
alias condaenvs="conda info --envs"

## WSL
alias perf='sudo /usr/lib/linux-tools-5.15.0-107/perf'
