#!/bin/bash
# vim: filetype=sh
# bash_locals
# Description: contains shell functions, variables, aliases etc
#   specific to local machine.

## ENVIRONMENT VARIABLES
## =====================

## PATH
export PATH=$HOME/.local/bin:$PATH

## VARIABLES
## =========

src="$HOME/src"
pjs="$src/projects"
dotfiles="$src/cli/dotfiles"

## ALIASES
## =======

# vim
alias vim="nvim"

## user aliases
alias scipy="ipython --profile=scipy"
alias letssketch="cd $pjs/sketchpad"
alias condaenvs="conda info --envs"

if [[ "$OSTYPE" == "darwin"* ]]; then
    # git
    alias yb="git branch | fzf | awk -v ORS= '{\$1=\$1};1' | pbcopy"
    alias gd="git log | yank"
    
    ## web-search aliases
    alias so="s -p stackoverflow"
    alias explainshell="s -p explainshell"
    alias github="s -p github"
    alias gdocs="s -p googledocs"

    # finder
    alias findershow='defaults write com.apple.finder ShowAllFiles TRUE'
    alias finderhide='defaults write com.apple.finder ShowAllFiles FALSE'
fi