#!/bin/bash
# vim: filetype=sh
# bash_locals
# Description: contains shell functions, variables, aliases etc
#   specific to local machine.

## ENVIRONMENT VARIABLES
## =====================

## PATH
export PATH="$HOME/src/mongodb/bin:$PATH"
export PATH=$HOME/.local/bin:$PATH
export PATH="$HOME/src/mjpro150/bin:$PATH"
export PATH="$HOME/anaconda3/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="$HOME/src/go/bin:$PATH"
export PATH="$HOME/src/spark/bin:$PATH"

export GOPATH="$HOME/src/go"

## VARIABLES
## =========

src="$HOME/src"
py="$src/Python"
pjs="$src/projects"
dotfiles="$src/cli/dotfiles"

## ALIASES
## =======

# vim
alias vim="nvim"

# git
alias yb="git branch | fzf | awk -v ORS= '{\$1=\$1};1' | pbcopy"
alias gd="git log | yank"

## user aliases
alias scipy="ipython --profile=scipy"
alias letssketch="cd $pjs/sketchpad"
alias condaenvs="conda info --envs"

## web-search aliases
alias so="s -p stackoverflow"
alias explainshell="s -p explainshell"
alias github="s -p github"
alias gdocs="s -p googledocs"

# finder
alias findershow='defaults write com.apple.finder ShowAllFiles TRUE'
alias finderhide='defaults write com.apple.finder ShowAllFiles FALSE'

# hy
if command -v hy >/dev/null; then
    alias hy="hy --repl-output-fn=hy.contrib.hy-repr.hy-repr"
fi
