set nocompatible              " be iMproved, required
filetype off                  " required

colorscheme elflord

" Place backup files in an alternate directory so they don't clutter working space
" (Make sure the directory exists; it will try each until one works)
" Not being used while noswapfile is enabled
set directory=$HOME/.backup,$HOME/tmp,$HOME
set backupdir=$HOME/.backup,$HOME/tmp,$HOME

" Visually show TABs and trailing whitespace
set listchars=tab:»\ ,trail:·

" Allows for magic like /* vim: tw=60 ts=2: */, but is a potential security vulnerability
set modeline

" Replace tabs with spaces
set expandtab
set shiftwidth=4
set tabstop=4

" Allows deletion past an append and similar
set backspace=indent,eol,start

" Use syntax highlighting/indentation based on filetype
syntax on
filetype indent plugin on

" Show line numbers in left column
set number
highlight LineNr ctermfg=grey

" Always use UTF-8 encoding
set encoding=utf-8

" Don't generate swp files
set noswapfile

" highlight matches
set hlsearch

" allow buffers to be hidden
set hidden

" no terminal error bells
set noerrorbells

" Increase cmd history length
set history=250

" Set vim undo stack depth
set undolevels=500

"" -- Environment / Mappings --

let mapleader=","
" Easier buffer spliting
nnoremap <leader>vs :vsp<cr>
nnoremap <leader>hs :sp<cr>
" Clear highlighting
nnoremap <leader>ch :noh<cr>
augroup env
    " Remove trailing whitespace prior to writing file
    autocmd BufWritePre * %s/\s\+$//e
    " Automatically reload vimrc after saving
    autocmd BufWritePost $MYVIMRC source %
augroup END

"" -- Filetype Headers --
autocmd BufNewfile *.sh so $HOME/.vim/headers/bash.vim
